name: Build Calc Application

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build project with Maven
      run: |
        mvn -B clean install

    - name: Test project with Maven
      run: |
        mvn test
        
  soos_dast_analysis_example:
    name: SOOS DAST Analysis Example
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Analysis
        uses: soos-io/soos-dast-github-action@v2
        with:
          client_id: ffqi908c9
          api_key: NmEzMTFhYmItMzE3Ni00NmRmLThkZjQtYWFjNGI1YmJhMTkw
          project_name: "Calculator"
          scan_mode: "baseline"
          api_url: "https://api.soos.io/api/"
          target_url: "https://localhost:8080/"
          
  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: java
          
      - name: Analyze with CodeQL
        uses: github/codeql-action/analyze@v1
        with:
          # Path to the sources directory to be analyzed
          # Adjust this path based on your project structure
          sources: .
          
  dependency-check:
    name: Dependency Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Dependency-Check
        uses: dependency-check/dependency-check-action@v2
      
      - name: Run Dependency-Check
        run: mvn dependency-check:check
